Ulepszenie podczas czyszczenia obrazów

diff --git a/.github/workflows/build-and-push.yml b/.github/workflows/build-and-push.yml
--- a/.github/workflows/build-and-push.yml
+++ b/.github/workflows/build-and-push.yml
@@ -37,4 +37,5 @@ jobs:
         run: docker logout
 
       - name: Cleanup Docker images
-        run: docker image rm ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}
+        run: docker image rm ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }} || echo "Image not found, skipping removal"
+
